version: '3'
services:

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    env_file:
      - ./env/letsencrypt.env
    ports:
      - 443:443
    networks:
      - proxy
    volumes:
      - letsencrypt-config:/config
      - certs:/etc/letsencrypt/live
    restart: unless-stopped

  openiot:
    image: richarvey/nginx-php-fpm:1.7.1
    container_name: openiot
    networks:
      - proxy
      - mqtt
    env_file:
      - ./env/openiot.env
    volumes:
      - ./public:/var/www/html
    ports:
      - 8888

  mqtt:
    build:
      context: ./docker/mqtt
    container_name: mqtt
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log

volumes:
  letsencrypt-config:
  mosquitto-data:
  mosquitto-logs:
  certs:

networks:
  proxy:
  mqtt:
