version: "3"
services:

  openiot:
    image: richarvey/nginx-php-fpm:1.7.1
    configs:
      - nginx
    networks:
      - frontend
	configs:
      - nginx
    volumes:
	  - public:/var/www/html
      

  mqtt:
    image: eclipse-mosquitto:1.6.1
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    configs:
      - mqtt

configs:
  nginx:
    file: nginx.conf
  mqtt:
    file: mosquitto.conf
  firebase:
    file: firebase.json

volumes:
  mosquitto-data:
  mosquitto-logs:

networks:
  frontend:
  backend:
